### ISSUE TITLE
reduceSeries doesn't work as explained.

### ISSUE THREAD

**Issue by avi-ram** [graphite-project/graphite-web#1066]
Reduce series with asPercent does not work as explained. Test to illustrate problem:

```
    def test_reduceSeries_asPercent(self):
        seriesList = [
            TimeSeries('group.server1.bytes_used',0,1,1,[1]),
            TimeSeries('group.server1.total_bytes',0,1,1,[2]),
            TimeSeries('group.server2.bytes_used',0,1,1,[3]),
            TimeSeries('group.server2.total_bytes',0,1,1,[4]),
        ]
        for series in seriesList:
            series.pathExpression = "tempPath"
        expectedResult   = [
            TimeSeries('group.server1.reduce.asPercent',0,1,1,[50]), #100*1/2 
            TimeSeries('group.server2.reduce.asPercent',0,1,1,[75])  #100*3/4 
        ]
        mappedResult = [seriesList[0]],[seriesList[1]], [seriesList[2]],[seriesList[3]]
        results = functions.reduceSeries({}, copy.deepcopy(mappedResult), "asPercent", 2, "bytes_used", "total_bytes")
        self.assertEqual(results,expectedResult)
```

The function return 100xbytes_used/(bytes_used+total_bytes) instead of 100xbytes_used/total_bytes. Thus values obtained are 33.33333333333333 (100x1/3) and 42.857142857142854 (100x3/7) instead of 50 and 75 respectively.

**Comment by languitar** [comment]
I just stumbled across this as well.

I think there is a definition problem now whether reduce should call the reduction function with a series list or with multiple arguments. But since series lists as the first argument are generally supported by nearly all functions, using multiple arguments would be much more useful because many functions do not support a series list as their second argument.
