### ISSUE TITLE
Inconsistent graphs using memcached with clustered graphite

### ISSUE THREAD

**Issue by arma26** [graphite-project/graphite-web#1102]
Hello, I'm getting inconsistent results when memcached is enabled across my 4 node cluster. Each node has 4 caches behind 1 relay. Graphite performs as expected with memcached disabled (commenting out MEMCACHE_HOSTS), albeit with higher cpu usage. The issue occurs both when picking 1 node and having the remaining nodes use it's memcached instance and when each node has it's own memcached instance.

Please note the time at the top right of the images, this is occurring between refreshes. This isn't limited to collectd metrics, but collectd's metrics don't contain my domain name. The cluster is running at REPLICATION_FACTOR = 2.

1: http://i.imgur.com/HWLm1bw.png
2: http://i.imgur.com/OwFEPB1.png
3: http://i.imgur.com/jSOavnl.png
4: http://i.imgur.com/xi2f8zU.png

These pictures were taken from only 1 node, however all nodes show identical results, even when each has it's own memcached instance. All the nodes are sharing the same mysql db so that I can use the same dashboards across all the nodes as I load balance between them.

On branch 0.9.x 5a4b3be420fad31fddcd883a71e5b2c8fc5f2296

**Comment by obfuscurity** [comment]
Only your frontend render host(s) should use memcached. You should not use it with any of your backend graphite-web instances. If you're running multiple frontend webs, use a shared memcached across all of them.

**Comment by deniszh** [comment]
I think we need to include that warning in release notes for 0.9.13, I'l
make a PR
I'm also wondering why local memcached is not working. @bmhatfield, what do
you think?

6:59, вт, 13.01.2015, Jason Dixon <notifications@github.com>:

**Comment by bmhatfield** [comment]
Was this behavior experienced before #1010 and #1026? Or is it new since upgrading?

When tracing this out for the issue filed with 1010, I'm not sure what would lead to this. There's an interaction somewhere that I haven't picked up on.

**Comment by obfuscurity** [comment]
@deniszh @bmhatfield You *should* expect inconsistencies when using memcached on backend nodes (in a multi-node cluster). This is not surprising. We should absolutely have documentation explaining how to use memcached *properly* but this report does not signify any sort of regression in my mind.

**Comment by deniszh** [comment]
@bmhatfield - as far as I understand @arma26 have same problems as @lamont in https://github.com/graphite-project/graphite-web/issues/1022. I'm also see no difference between enabling and disabling memcache, but if it breaks something after upgrade to 0.9.13 we need to warn users then...
@obfuscurity - I was quite sure that we need to disable shared memcached and single memcached instance works fine. But if not - it's also OK, we just need to include something like "Change in clustering: if you are using clustering graphite with REPLICATION_FACTOR >= 2 you need to disable memcache caching" in release notes.
Is it good idea to do so? I think it will spare some questions and github issues after release...

**Comment by arma26** [comment]
The issue was resolved when I disabled memcache across all storage nodes and spun up a 5th graphite-web instance with memcache enabled.

**Comment by jssjr** [comment]
Will someone please explain why memcached caching should be disabled on clustered graphite with replication factor >= 2?

**Comment by lamont** [comment]
Well, it depends on how your cluster is setup. Mine was two tier with  front-end webui nodes that list a bunch of backend storage nodes in the cluster, but the backend nodes are unaware of each other. Originally I had every machine in the cluster sharing a global memcache cluster, and everything was fine. 

Patch 1010 changed from fetching individual metrics from each backend (after a parallel "what metrics does this backend have that satisfy this wildcard query") to asking for the raw series results to the original wildcard query against each backend. That caused results returned from backend node A to be cached and visible to backend node B. So when all backend nodes shared the same memcache cluster, you'd start getting the same results from each node in the backend. I doubt the replication factor matters, it was just that the designer of patch 1010 didn't anticipate a global memcache pool, and there was no good reason for me to have one. 

I changed it so that each backend node used only a local memcache store and everything was fine. You want the local memcache store so that the expensive /metrics/find requests are cached for a few minutes between all the processes serving web requests on the backend. If the proposal is to namespace the request cache with the local node address, that seems like a good solution as well, both for the problem I had and any future ones.
