### ISSUE TITLE
Feature Request: get a summarizeByMonth()

### ISSUE THREAD

**Issue by toni-moreno** [graphite-project/graphite-web#1214]
There is no way to get "real" summarize() by month instead of summarize('metric,'1month'), that it really summarize each 30 days.

by example, when we do a request for January we want from 1 to 31.

**Comment by EdstromP** [comment]
I agree. I have a graph displaying accumulated gas consumtion since a couple of years ago and would like to add a table showing the value of the end of each month. I've tried **summarize(foo.bar.h2, "1month", "last")** but depending on the currently chosen time range, I get different results.
Is there any workaround to achieve this?
