### ISSUE TITLE
pip re-installs carbon and graphite-web packages on every run

### ISSUE THREAD

**Issue by bigunyak** [graphite-project/graphite-web#1228]
Hi there,

While writing puppet manifest files to automate graphite installation I notices that `carbon` and `graphite-web` pip packages get re-installed on every run. Pip normally doesn't install already installed packages and exits with "Requirement already satisfied" message unless you specify `--upgrade` option.
The interesting thing that `whisper` package does not get re-installed.
I believe the problem is that pip can not figure out that `carbon` and `graphite-web` packages are already in the system and `pip list` command proves that, in the output it produces you'll find `whisper` package only, `carbon` and `graphite-web` are not listed.
I wonder if this problem could be fixed as re-installing the packages with every pip run is not an expected behavior really.
I should mention that the problem is apparently a pretty old one as it was already reported over two years ago here:
http://serverfault.com/questions/416489/how-to-tell-puppet-to-only-install-using-pip-if-a-file-doesnt-exist

Dmitry

**Comment by brutasse** [comment]
That's because of the install prefix: carbon and graphite-web are installed under `/opt/graphite` by default and pip doesn't know about that. Whisper doesn't have a hardcoded prefix.

You should be able to override the prefixed installation by passing `--install-option="--prefix=/usr" --install-option="--install-lib=/usr/lib/python2.7/site-packages/"` as options to the `pip install` command (or change to whatever prefix/python version you need).

**Comment by piotr1212** [comment]
another reason for https://github.com/graphite-project/graphite-web/pull/2409
