### ISSUE TITLE
divideSeries not working in reduceSeries

### ISSUE THREAD

**Issue by cschotke** [graphite-project/graphite-web#1299]
I cannot get 'divideSeries' to work with reduceSeries. For example, the following works fine: ```reduce(map(SERVER008.diskinfo.*.*,2),"asPercent", 3, "used_bytes", "total_bytes")``` 

but it errors out if I change it to:
 ```reduce(map(SERVER008.diskinfo.*.*,2),"divideSeries", 3, "used_bytes", "total_bytes")```

with this exception: `Exception Value: divideSeries() takes exactly 3 arguments (2 given)`

I see this same behavior on any map/reduce I test. `asPercent` and `diffSeries` work fine, but it errors out whenever I try to use `divideSeries`.

**Comment by jkeifer** [comment]
I also have a similar problem, and had to go digging into the source to figure out why.

And that reason why is because `reduce` supplies the "reduce function" with the metrics that match the "reduce matchers" as a series list. That is, your example calls `divideSeries([used_bytes, total_bytes])` when you really want to call `divideSeries(used_bytes, total_bytes)`. Notice this second version pass in two arguments, whereas the first only provides one argument (you may notice from the exception that `divideSeries` takes a third argument internally, which is the HTTP request context, but you don't need to worry about that)

In fact, because of this behavior, the example used in the docs for `reduceSeries` (which you are effectively trying to replicate here) does not seem like it would result in the correct values. As you probably realized, your example

    reduce(map(SERVER008.diskinfo.*.*,2),"asPercent", 3, "used_bytes", "total_bytes")

gives you `100 * used_bytes / (used_bytes + total_bytes)`, not `100 * used_bytes / (total_bytes)`.

I believe one option to fix `reduce` so it actually works would be to accept lists of "reduce matchers" for each argument to be passed into the reduce function. Thus, in your case, you would call

    reduce(map(SERVER008.diskinfo.*.*,2),"divideSeries", 3, ["used_bytes"], ["total_bytes"])

However, I am not part of the graphite team and cannot make such a decision. I will likely put in a pull request for a new reduce function that would work in such a manner; whether that pull request gets included is up to someone else.

**Comment by jkeifer** [comment]
Note that I spoke too soon. It appears that others have already noticed this problem and have solved it. We apparently both need to update. See issues #1066 and #1265.

**Comment by obfuscurity** [comment]
Indeed, this has been fixed in master.
