### ISSUE TITLE
Graphite  performance issue

### ISSUE THREAD

**Issue by ravibhooshan** [graphite-project/graphite-web#1314]
Hi All,
I need some expert suggestion on improving graphite performance.
I am running below architecture:
One relay behind F5 VIP
4 carbon servers
Relay is using consistent hashing and replication factor -4 
All are running on physical server on centos with 6 CPUs (4 cores each), 64GB RAM and 800GB SSD.
No of carbon creates - 75
rest all settings as default.
Till 500-600k metrics per minutes i was not having any issue.
Now we are hitting 1.5 Million metric / minute.

On each release day we are adding 300-400k metric and during release  (in 30 minutes) we used to push around 300-400k metrics and that is where problem starts.
Data starts queuing up and see 80% data getting dropped at relay. It takes around 2-3 days to normalize.

I thought it because of carbon-cache is not completing metric in  time so planned to run multiple caches and crested 3 caches on 2 of carbon servers. But that is also not solving the issue.

Other issue i facing is that in multi-cache i am running child relay on carbon server using rules.file. But relays rules is not directing data on the basis of regex.

Please let me know how to improve data flow from relay to carbon-cache. Please let me knwo if you have question.

**Comment by ashokrajar** [comment]
Quick thing to try is to add one/two more relay servers behind the VIP.

What is the load/IO/mem stats on relay & carbon-cache servers ?

If I understand correctly you are running one carbon-cache daemon per 24 core server. That means you are under utilizing the hardware. Carbon can't take advantage of the multi-cores though you have 24 cores but carbon will still utilize only one core. You should be running as many as carbon-daemons possible based on your disk IOPS.

Thumb rule is no. carbon-cache daemons = no. cores. But in you case if you run 24 carbon-cache daemons then you may hit the disk IOPS limitations and all the process will suffer from IO wait. So you need to carefully choose the no. of carbon-cache daemons w.r.t your disk IO. Multiple small SSD disks with RAID-10(eg: 12 X 128GB SSD with RAID10) instead of one beefy disk can be a good option.

That said then your replication factor also has to be set to a higher value for such a complicated setup. And number of relay servers also has to be increased. If your F5 VIP can do port level load balancing then you can run multiple relay-daemons on different ports on the same servers similar to cache. Unlike carbon-cache relay doesn't require any storage so I would say a pool of tiny servers for relay(even a single/dual core is enough per server).

**Comment by ravibhooshan** [comment]
Thanks Ashok.
My IO/Mem stats are average i means it is not stressed out.
I have 3 carbon-caches on 2 of four carbon cache server. But in multi-cache setup relay-rules.conf is not forwarding data as per regex.

**Comment by ashokrajar** [comment]
You will not hit the IO/Mem unless you are running as many carbon-cache servers per cpu core and they are stressed by millions & millions of metrics.

Take a look at this blog which explains how to do clustering with graphite. I would strongly propose such setup  for you. I also have a similar setup in production but I have replaced the relay component with carbon-c-relay for performance and data loss issues. When carbon-relay/carbon-cache is under stress and when it hit the cpu limit(GIL) it stops accepting new metrics.

This is not a issue. It's more of a knowledge sharing & best practices in setting up a graphite cluster. So please close this issue and move this discussion to the mailing-list/IRC.

**Comment by ravibhooshan** [comment]
Thanks again Ashok. I was planning to move on to relay-c.
I think you missed to add blog url.Please send me blog link.

**Comment by ashokrajar** [comment]
Sorry about the link. Here is it https://grey-boundary.io/the-architecture-of-clustering-graphite/
