### ISSUE TITLE
weightedAverage throws IndexError

### ISSUE THREAD

**Issue by joafri** [graphite-project/graphite-web#1389]
I get this when I try to apply a "nonNegativeDerevative" on my networkdata in graphite:

```
Traceback (most recent call last): File 
;/usr/lib/python2.7/site-packages/django/core/handlers/base.py
;, line 113, in get_response response = callback(request, *callback_args, **callback_kwargs) File 
;/opt/graphite/webapp/graphite/render/views.py
;, line 112, in renderView seriesList = evaluateTarget(requestContext, target) File 
;/opt/graphite/webapp/graphite/render/evaluator.py
;, line 8, in evaluateTarget result = evaluateTokens(requestContext, tokens) File 
;/opt/graphite/webapp/graphite/render/evaluator.py
;, line 29, in evaluateTokens return evaluateTokens(requestContext, tokens.expression, replacements) File 
;/opt/graphite/webapp/graphite/render/evaluator.py
;, line 54, in evaluateTokens args = [evaluateTokens(requestContext, arg, replacements) for arg in tokens.call.args] File 
;/opt/graphite/webapp/graphite/render/evaluator.py
;, line 29, in evaluateTokens return evaluateTokens(requestContext, tokens.expression, replacements) File 
;/opt/graphite/webapp/graphite/render/evaluator.py
;, line 58, in evaluateTokens return func(requestContext, *args, **kwargs) File 
;/opt/graphite/webapp/graphite/render/functions.py
;, line 679, in weightedAverage sumProducts=sumSeries(requestContext, productList)[0] IndexError: list index out of range
```

**Comment by joafri** [comment]
We can close this - I found the issue.
I sent new data to carbon once per 60 seconds.
When I checked the log in chrome in developerview (F12) then I saw that I got two null and one line with data for every minute.
I changed the rate of date to carbon to once per 10 seconds and voila - the graphs started to work fine.

This feels like a workaround thou and I belive that the graphing should be able to handle null by ignoring them maybe?

**Comment by obfuscurity** [comment]
The problem is not with `nonNegativeDerevative`, it's with your use of `weightedAverage`. More specifically, it looks like `sumSeries` is returning an empty result in line 679; probably because `productList` is empty. We try to grab the first result (`[0]`) which causes the `IndexError: list index out of range`.

This isn't a bug per se, in that we can't return a valid series where data doesn't exist, but it feels like we could raise a better exception message. Can you provide the actual render query you're trying to run?
