### ISSUE TITLE
Install docs / pip installation is broken

### ISSUE THREAD

**Issue by jvanasco** [graphite-project/graphite-web#1509]
I tried installing from PIP into a virtualenv using the docs.

This method is very broken.

pypi installs `0.9.15`, however this doesn't contain any information on dependencies -- so they're not automatically attempted.

the actual dependencies aren't listed in the docs or the pypi download.

the latest versions of django or django-tagging both seem to be incompatible with graphite in different ways as well.

the closest thing I found was the `requirements.txt` for the 0.9.15 tag (and master) both all list non-dependencies, re-list things like the whisper client (which is pegged to a git version, not the pypi version that the installation instructions give), and list things that are not compatible.

Installing these via pip should work:

    pip install Django==1.4
    pip install django-tagging==0.3.1
    pip install pytz

I was not able to find a version of whitenoise that would work.  the 3.0 branch wants a django with `django.utils.six`, the 2.x branch raises errors on a url component split.

The docs should reflect an install procedure that could actuall work.

There should be an actual functional set of requirements for a given release as well.

**Comment by obfuscurity** [comment]
@jvanasco If you're still interested, I'd appreciate your feedback with the latest versions of the install documents and updated setuptools for pip.

http://graphite.readthedocs.io/en/latest/install.html
http://graphite.readthedocs.io/en/latest/install-virtualenv.html
http://graphite.readthedocs.io/en/latest/install-pip.html

This process has been updated so that anyone installing from these ("latest") docs should get the proper versions of each Graphite component (currently on version `0.10.0-rc1`). It should also handle all *required* Python package dependencies, and where it doesn't, should document the needed vendor packages (e.g. Python or Cairo headers).

It's certainly possible there are still some rough edges, but I've run through this a couple times now and knocked out all of the obvious bugs.

If you're *not* interested in testing this out or you've moved on to a different installation process (or entirely different TSDB), that's ok too, just let me know so we can close this issue. Sincerely, thanks for your feedback.

**Comment by jvanasco** [comment]
I'm deploying a new Ubuntu image next week -- I'll put this on my task list!

**Comment by obfuscurity** [comment]
Awesome, thanks @jvanasco. I hope you don't mind, I'm going to close this issue for now but I'm looking forward to hearing back from you.

**Comment by jvanasco** [comment]
I think this seems to be working.

glad to see pycairo replaced.  fwiw, these were my old build notes to patch pycairo to get around errors:

	cd ~/build
	wget http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2
	bzip2 -d py2cairo-1.10.0.tar.bz2
	tar -xf py2cairo-1.10.0.tar
	cd py2cairo-1.10.0
	# wget http://cvsweb.netbsd.org/bsdweb.cgi/~checkout~/pkgsrc/graphics/py-cairo3/patches/patch-.waf3-1.6.4-e3c1e08604b18a10567cfcd2d02eb6e6_waflib_Tools_python.py?rev=1.1&content-type=text/plain&only_with_tag=MAIN
	# patch -p3 .waf-1.6.3-3c3129a3ec8fb4a5bbc7ba3161463b22/waflib/Tools/python.py < patch-.waf3-1.6.4-e3c1e08604b18a10567cfcd2d02eb6e6_waflib_Tools_python.py\?rev\=1.1
	./waf configure --prefix=/opt/graphite/
	./waf build
	./waf install
