### ISSUE TITLE
MaxDataPoints and default consolidate function

### ISSUE THREAD

**Issue by ctrochalakis** [graphite-project/graphite-web#1525]
I was trying to debug an issue with a counter graph in grafana. The numbers would not add up to the expected value. The issue was that grafana sets the maxDataPoints (added in #170) parameter which calls `consolidate()` under the hood and `consildate()` aggregates by average.

What we did was set the `consolidateBy(sum)` to force a sum aggregation function but that doesn't seem quite right. Whisper is already aware of the preferred `aggregationMethod` for the metric (as set by carbon storage aggregation settings) so I believe this value should be the default, and not 'average'.

@philiphoy @gingerlime what do you think?

**Comment by dhellema** [comment]
No idea what the status of this request is but indeed this is rather unexpected behaviour. Counters (only adding up) are being averaged due to maxDataPoints and the default 'avg' of consolidate() which is incorrect in such case. Having to add consolidateBy(max) each time is rather annoying.

I hope this can be fixed :-)

**Comment by Dieterbe** [comment]
I used to unconditionally agree with that, see http://dieter.plaetinck.be/post/25-graphite-grafana-statsd-gotchas/#runtime.consolidation
i've been working on an alternative backend for graphite which does this. but then a colleague of mine (@DanCech) pointed out this isn't always right, specifically not when combined with specific processing functions like summarize. you can read the entire discussion here https://github.com/raintank/metrictank/issues/463

**Comment by fred777** [comment]
Hi! Seems I have something to add here....

I'm running latest docker containers of hopsoft/graphite-statsd and grafana/grafana and collecting metrics via codahale graphite reporter which pushes data every 10s.

Graphite seems to be at v0.9.15.

Now, I'm having issues with different counter metrics, e.g. a "Jobs Running" counter which gets incremented when a batch job is scheduled and decremented when it's done.

This is my query: consolidateBy(forecastservice.service.batch.runningjobs.ConsumptionAveragerBatchJob.testforecast.count,"max")

The number of running jobs never exceeds 1, but as soon as the visualized time span gets too big, the displayed maximum is much higher.

![image](https://user-images.githubusercontent.com/5749774/29072628-b953976c-7c48-11e7-9521-c272ac6dc32f.png)

![image](https://user-images.githubusercontent.com/5749774/29072655-da109248-7c48-11e7-8803-0b52f1107934.png)

I've played around with consolidateBy min, max, avr. sum, but it doesn't make a difference, nor does leaving out consolidateBy.


I bet that this has to do with the fact that I'm displaying a counter which somewhat get's summed up - the number of running jobs is a 1 for 60 seconds - hence there are 6 data points with counter-value 1.

Looks like consolidateBy always sums a counter....

Is there any workaround? (Of course, I could implement my own counter and report it as a gauge, but this would be my last resort...)

Or has this been fixed in a later version of graphite? (Didn't see something in change logs)
