### ISSUE TITLE
Document version in which functions were added

### ISSUE THREAD

**Issue by OrangeDog** [graphite-project/graphite-web#1751]
It would be useful if http://graphite.readthedocs.io/en/latest/functions.html included the version in which each function were added.
At the moment I have to rely on checking back through http://graphite.readthedocs.io/en/latest/releases.html, but this is cumbersome (and 0.9.13 is missing).

**Comment by NotSqrt** [comment]
So many functions evolved between 0.9.15 and the latest doc !
Documenting those changes would be very useful !

**Comment by obfuscurity** [comment]
Because the documentation for functions is derived from the inline comments among the code, it would a) involve tons of research and b) really muck up the `git blame`.

I'm open to suggestions on how this would best be accomplished without diverting precious developer resources and cluttering up our commit history.

**Comment by NotSqrt** [comment]
Here is an example in django's documentation : https://github.com/django/django/blob/1.8.16/docs/topics/http/shortcuts.txt#L49

So this stuff can have its life in a separate documentation ..

**Comment by obfuscurity** [comment]
Yes, that's a handy format for sure. Not sure that it addresses any of my concerns. Are you proposing we rip all of the documentation out and make it standalone? Because that's even more of a resource demand than simply adding comments to the existing documentation source.

**Comment by NotSqrt** [comment]
I think the most frustrating thing is that the doc on readthedocs shows the master state by default, not the latest release.

For instance, asPercent changed to allow a list of series as second argument.
I was so happy to finally upgrade to graphite-web==0.9.15, just for this, but no, it's just in the master, not any released version despite being developed 6 months ago.

**Comment by obfuscurity** [comment]
I totally understand and empathize. If you look at http://graphite.readthedocs.io/en/0.9.15/functions.html instead of http://graphite.readthedocs.io/en/latest/functions.html then you're seeing the correct docs for your version.

**Comment by NotSqrt** [comment]
Thanks !

Any visibility on the next release ?

**Comment by OrangeDog** [comment]
> involve tons of research
Better that one person does it and puts it in the docs, rather than every user has to do it themselves.

**Comment by deniszh** [comment]
We can reuse @dgryski's info from https://github.com/dgryski/carbonapi/blob/master/COMPATIBILITY.md#functions

**Comment by dgryski** [comment]
That was mostly scraped together by @nnuss.  It's not complete and of course focused on things `carbonapi` does or doesn't support, as determined by people at $WORK complaining that they're graphs don't work.

**Comment by nnuss** [comment]
Some minor(?) points:
* That table was last substantially updated in July. I just skimmed the changes in functions.py and added `delay()`.
* The table lists the first release occurance of a function as it appears _now_ and this might differ from @OrangeDog's original request. Notably it lists `cactiStyle()` as "latest" because of b347316e95830a392684367419c82309b730ff11 but it was first introduced **long** ago in 7328a8d2a700b38e6a3b80dd31f8ab3c9b567766 (0.9.9) and the change to specify the units in a52ef41e66a124ecfb7bc51bd72d0c6fccc20817 would have coincided with 0.9.11 had it been in the 0.9.x branch.

**Comment by NotSqrt** [comment]
Sphinx has the required tools to add the version info in the function docstrings : http://www.sphinx-doc.org/en/stable/markup/para.html : `versionadded`, `versionchanged`, `deprecated`
