### ISSUE TITLE
Fetching latest not null metric from Graphite

### ISSUE THREAD

**Issue by ajcs3** [graphite-project/graphite-web#1803]
My use case is to fetch the latest not null metric from graphite and plot it in Grafana. Can anyone help me how I can achieve it?
This is my data point hierarchy sample:
p1.p2.p3.metric1
p1.p2.p3.metric2
p1.p2.p3.metric3
In the above datapoints I want to get latest updated metric 'metric1' for 'p2' where inside 'p2' there are multiple variants of 'p3' where each of 'p3' has its own metrics like 'metric1', 'metric2' and 'metric3'
If I can get the max value of 'p3' and fetch the corresponding metric against it, that would solve my purpose.
I tried with MaxSeries and Summarize but the problem is that both of them are not working. Any suggestions would help.

**Comment by deniszh** [comment]
Try to use [currentAbove](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.currentAbove)([transformNull](https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.transformNull)(...,0),0)

**Comment by ajaycsse** [comment]
Thanks for the reply. 
Can we apply the functions on the second last datapoint for example on 'p3' i.e. getting highestMax of 'p3' , because whats happening is it again pulls me latest of all the metrics 'metric1' for all the different 'p3' varients available. What I need is to pull highestMax('p3') and pull related corresponding metric 'metric1' for that 'p3'.

**Comment by deniszh** [comment]
Sorry, @ajaycsse, I don't really understand what you trying to achieve. :(
Could you please explain a bit more?

**Comment by ajaycsse** [comment]
Suppose I have the following sample hierarchy in Graphite.

website.API.version.pagenumber.response
If I want to extract the response time for the highest page number, how do I do it? It sounded simple but I can't seem to get it. I try to use the maxSeries function but it's instead giving me the maximum response time out of all the pagenumbers rather than the response time from highest page number. I'm not able to apply the maxSeries function on the second last column.

**Comment by nnuss** [comment]
// A little more concrete set - replacing `pagenumber` with acutal numbers
```
website.API.version.1.response
website.API.version.2.response
...
website.API.version.99.response
```

Where the upper bound of `pagenumber` is not known (but in this example 99):

You want:  `website.API.version.99.response`

Is that what you would like to achieve?

**Comment by ajaycsse** [comment]
@nnuss Thanks for understanding in detail.
Yes that's what I like to achieve. Could you please provide a way to achieve it.

**Comment by nnuss** [comment]
The closest I can conjure up is:
`limit(sortByName(website.API.version.*.response),1)` // requires 0.9.14+
but that gives the pagenumber which is first in sort order (lowest -or- with highest leading digits ;  depending on how you use sortByName).

You seem to need at least one of:
- `sortByName(seriesList, natural=False, descending=False)` : support descending order
- `reverse(seriesList)` : new function to reverse ordering
- `limit(seriesList, n)` : support negative indexing for 'n' (from the end of the list)
- `first(seriesList, n)` / `last(seriesList,n)` : alias first() and limit() / make new last() function

However. If `pagenumber` is not the first variable element in the names even those above may not be enough.

**Comment by ajaycsse** [comment]
@nnuss Thanks for the suggestions. Sortbyname is not working in my graphite version. But I tried with sortByMaxima and limit together and it almost solved my issue. But I am getting the second highest pagenumber by this approach. Any suggestions what can be done to get the first highest one instead of second highest one

**Comment by nnuss** [comment]
sortByMaxima() examines series **data points** to perform the sort.
In fact limit(sortByMaxima(),n) gives the same behavior as highestMax().

What we described above (locating highest pagenumber node) needs sorting of the series **name** to select the desired metric.

These are functions I spot that operate over the name alone:
- alias & aliasByMetric & aliasByNode & aliasSub
- exclude & grep
- sortByName
- substr
