### ISSUE TITLE
Improve render performance

### ISSUE THREAD

**Issue by wy92** [graphite-project/graphite-web#1915]
We have encountered some performance issues when many data points are involved in functions computation, such as summarize, sumSeries, etc. 

For example, our metric's resolution is mainly `10s:1d`,  `summarize(span.*.client.*.app1.*.request_time.percentile.95, "7d")`, this query may involve many metrics and cost more than 10 seconds, we discover that the cpu utility is almost 100%, and mainly is user cpu, so we assume the bottleneck is in `summarize`.

We are working on it, and have some ideas, we would like to know what is the official plan about this and see if we can work together.

This is our initial idea:
* we first parse target, generate a plan and merge plan, and then execute the plan.
* assume the query's from=`from1`, until=`until1`，we separate the interval into N partitions, and process each partition with a new graphite-web request.

**Comment by deniszh** [comment]
The official plan - made Graphite better, without breaking it. If you're proposing some radical changes - we can merge it to master and release later, in some 1.1.x release. If your changes fixing some problem and are not bringing troubles - we can even include that in a current stable release.

**Comment by deniszh** [comment]
Ah, one more thing - all breaking changes should be configurable by config file and disabled by default.

**Comment by DanCech** [comment]
Looking at summarize there are definitely some gains to be made internally since right now it uses a multi-step process and generates an intermediate list of buckets.  I have a rough patch to reduce that so it only walks the data once, you can try that out in https://github.com/graphite-project/graphite-web/tree/summarize if you're interested.  In my testing I'm seeing about a 40% reduction in the time spent in summarize()

**Comment by deniszh** [comment]
@wy92 - sorry for bugging you, but did you have a chance to test @DanCech's patch?

**Comment by reyjrar** [comment]
Was looking for a place to converse, but I'm seeing another major performance degradation on queries with large numbers of metrics.  In older 0.9.15 versions of graphite, I could get a dataset of 10,000 metrics to return in under 20 seconds.. Now in 1.0.2, that same query is taking upwards of 90 seconds.  Group, filtering, and combining functions also fail because the fetch for the data takes too long.

I'm stuck on pre-1.x.x because most of queries select data from thousands of metrics and display the most interesting ones.  I think this is related to the OP's bug.
