### ISSUE TITLE
Make finders able to handle events

### ISSUE THREAD

**Issue by iksaif** [graphite-project/graphite-web#1944]
Events are pretty useful but sould ideally be stored in the same database as the timeseries.
We have two ways of doing that:
1. Add in to the finder API
2. Create another kind of "module" for events

One could argue that we should use the Django database plugins for that, but if somebody is already using Cassandra/ES/Riak to store timeseries it's probably a better idea to use the same database instead of depending on MySQL / PostgreSQL for events. 

What do you prefer ?

**Comment by DanCech** [comment]
When you say events are you referring to things like annotations?  I'd argue that expanding into that arena is something that doesn't add a lot of value for most users, especially since Grafana now includes annotation functionality, and as you say a lot of folks are already using ES etc.  What do you see as the advantage for the user of having events in graphite?

**Comment by deniszh** [comment]
Grafana's annotations are only showing annotations, it still relies on some storage. [Graphite events API](https://graphite.readthedocs.io/en/latest/events.html) is used by many people, it's already there, we should support it in the backward compatible way IMO. We can introduce another API for events, sure, though.
I don't really like that it's stored in Django database, we should find some pluggable/configurable way where we can store it - OTOH current API is quite verbose and requiring to store bunch of strings data (message and list of tags, tags should be searchable) - so, I doubt that can be easy done with most of KV/NoSQL storages.

**Comment by DanCech** [comment]
Actually Grafana now has support for storing annotations in its own database.

**Comment by deniszh** [comment]
@DanCech : Ah, didn't know that. Maybe it's in beta? [Annotation documentation](http://docs.grafana.org/reference/annotations/) says nothing about it, and I see nothing in latest stable Grafana.

We're still using normal Graphite annotations (like `drawAsInfinite(my.releases)`) but still planning a move to Graphite events or ES, because it has tags or ability to add some text mark to it.
I'm not sure what we going to do here. 
Normal Graphite annotations are very limited but working for every backend, even now.
Events API looks great but has a burden of SQL storage.
We can introduce different storage, but it will require that storage instead of SQL for events.
Ideal solution IMO - left Events API as is, but make it works with pluggable backends, but not Django related (e.g. most popular, MySQL / PostgreSQL / Cassandra / Riak / Mongo, with migration tool from current backend).
If we're OK to proceed - I can spend some time on it, we would like to use something similar.

**Comment by deniszh** [comment]
OTOH - doing so many backend w/o django db abstraction layer could be... not quite easy task.
I do not know any existing sql/nosql db abstraction layer for python...

**Comment by iksaif** [comment]
@DanCech : yes, graphite events translate to annotations. Are you sure that Grafana can store them ?

@deniszh : the API for events is quite CRUD. I would have a default event plugin using Django's database, and custom ones using whatever people want.

**Comment by DanCech** [comment]
@iksaif I thought the updated annotation system had been merged, but it's still in development.  I just reached out to @torkelo for more info on the state of things.

**Comment by DanCech** [comment]
https://github.com/grafana/grafana/issues/1286#issuecomment-294281268
https://github.com/grafana/grafana/pull/8197

**Comment by iksaif** [comment]
I guess that if Grafana is going to get that feature, I'll be happy to deprecate it from Graphite.
