### ISSUE TITLE
Something is causing graph rendering to change between reloads

### ISSUE THREAD

**Issue by mleinart** [graphite-project/graphite-web#196]
#### Imported from https://bugs.launchpad.net/bugs/860161

|  |  |
| --- | --- |
| Reported by | [ohlol](https://launchpad.net/~ohlol) |
| Date Created | Sep 27, 2011 |

http://dl.dropbox.com/u/1613178/render1.png
http://dl.dropbox.com/u/1613178/render2.png
http://dl.dropbox.com/u/1613178/render3.png

The only difference beteween these three images is that I hit reload. It's not consistent (sometimes I can reload the same graph several times with no obvious variance).

**Comment by robertkosten** [comment]
Not sure it helps, but: I encountered this bug on and off for years and I finally got rid of it (it seems) since moving my retention policy from 7d to 8d for my charts showing the last week. That graphite doesn't necessarily play nice at the fringes is no secret and I assume the problem happens when microseconds determine which scaling to use, so that one series is still fully rendered within the 7d policy and the next series already within the larger one, leading to a scaling difference whenever the stars/microseconds align right.

**Comment by brianmcdonnell** [comment]
I've been experiencing the same/similar problem too and can add some details on the cause of the issue. I'm running graphite 1.0.1

As a test, I was running a query over the last 30 days, which the same target plotted 5 times. Almost every rendered graph would erroneously render 1 of the 5 series at a lower level to the others 4 correct series.  The magnitude of the error would change on every load (I disabled request caching).
**e.g. request:**
```
http://graphite.example.com/render/width=913&height=456
  &from=-30days
  &target=sumSeries(stats.counters.servers.*.request.count)
  &target=sumSeries(stats.counters.servers.*.request.count)
  &target=sumSeries(stats.counters.servers.*.request.count)
  &target=sumSeries(stats.counters.servers.*.request.count)
  &target=sumSeries(stats.counters.servers.*.request.count)
```

The bug is easy to spot when you request multiple identical targets because you'd expect the plotted series to always overlap.  It also increases the chances of the bug occurring on a single request because there are multiple opportunities for it to occur.

However, multiple plots are not required to produce the problem.  The following request will also occasionally render the series at incorrect scale.
```
http://graphite.example.com/render/width=913&height=456
  &from=-30days
  &target=sumSeries(stats.counters.servers.*.request.count)
```

As others have touched on, this bug comes up when the relative "from" date aligns with a retention policy threshold. Mine is as follows:
```
[stats]
pattern = ^stats.*
retentions = 1m:6d,10m:30d,1h:1y
```
When the relative "from" date aligns with a retention policy threshold AND the target involves loading multiple whisper files, some of the whisper files can load from one archive (in my case 10m:30d) while the remainder will load from the coarser grained archive (in my case 1h:1y).

In my example target above, the `sumSeries` function will receive results with a mixture of retention rates. The [docs describe](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.sumSeries) how `sumSeries` handles this:
> If metrics with different retention rates are combined, the coarsest metric is graphed, and the sum of the other metrics is averaged for the metrics with finer retention rates.
So `sumSeries` will roll my 10m counts into 60m counts data by averaging 6 10min values.  In my use-case the correct aggregation of these *counts* would have been to use `sum` rather than `average`.  Meaning metrics/whisper files that returned 10m values are under-represented by a factor of 1/6th in the final result.

So why does whisper sometimes return data from one archive and other times from another archive? The short answer is that it's a race condition that depends on how long it takes graphite to load all the whisper files needed for the request.

Assume this target matches 10 different metrics:
```
http://graphite.example.com/render/width=913&height=456
  &from=-30days
  &target=sumSeries(stats.counters.servers.*.request.count)
```

A whisper file for each of the following keys must be read.
```
stats.counters.servers.server01.request.count
stats.counters.servers.server02.request.count
stats.counters.servers.server03.request.count
...
stats.counters.servers.server10.request.count
```

In pseudocode, here's what happens:

```
for key in key_list:
  matching_nodes = finders.findNodes(key)
    for node in matching_nodes:
      node.fetch(startTime, endTime, now, requestContext) # Link 1
```
Link 1: https://github.com/graphite-project/graphite-web/blob/1.0.1/webapp/graphite/render/datalib.py#L125

`node.fetch` will in turn call [WhisperReader.fetch](https://github.com/graphite-project/graphite-web/blob/1.0.1/webapp/graphite/node.py#L32).  Crucially, it does not pass `now` as [WhisperReader.fetch](https://github.com/graphite-project/graphite-web/blob/1.0.1/webapp/graphite/readers.py#L186) does not accept this parameter.

Finally WhisperReader calls [whisper.fetch()](https://github.com/graphite-project/graphite-web/blob/1.0.1/webapp/graphite/readers.py#L186) but it cannot pass `now` as it doesn't have this value.

whisper.fetch supports an optional [now](https://github.com/graphite-project/whisper/blob/1.0.1/whisper.py#L820) argument, but instead is forced to calculate `now` [on the fly by getting the system time](https://github.com/graphite-project/whisper/blob/1.0.1/whisper.py#L839).

When working through the list of whisper files a wall-clock second can tick over.  Given that our query was literally on the threshold of 30day retention period, when reading the next whisper file, the `from` date will be `30days + 1 second` old and whisper.py will be forced to use the coarser-grained archive for the current and all subsequent whisper files.

**The Fix**
The solution, is to pass `now` all the way down to whisper.py, so it doesn't change from the loading of one whisper file to the next.

**Comment by deniszh** [comment]
Wow, nice debugging, @brianmcdonnell , thanks a lot!
datalib code was refactored in 1.1.x, but whisper.fetch() still not accepting now - https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/readers/whisper.py#L57
But fix should be quite easy - just propagate now through https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/readers/whisper.py#L54
Am I right, @DanCech ?

**Comment by DanCech** [comment]
What I've actually been considering is to have whisper use the file mtime when calculating available retentions rather than `now`, though that would potentially cause similar problems if files have differing mtime values.  Passing `now` through would definitely be a big improvement since whisper now supports it.
