### ISSUE TITLE
Custom finders - fetch multiple metrics

### ISSUE THREAD

**Issue by linar-jether** [graphite-project/graphite-web#2038]
Is there a proper way to fetch multiple metrics in a single request from a custom finder?
Similar to graphite_api's `fetch_multi`?

I saw support was added in the RemoteFinder for pre fetching batches, but couldn't find any documentation for it...

Any help with this will be appreciated

**Comment by deniszh** [comment]
I'm not sure that RemoteFinder's way is portable enough. Probably we need to backport [fetch_multi()](https://graphite-api.readthedocs.io/en/latest/finders.html#fetching-multiple-paths-at-once) from graphite-api.

**Comment by DanCech** [comment]
PR #2093 allows finders to expose `find_multi` and `fetch` methods, you can read the details in [BaseFinder](https://github.com/DanCech/graphite-web/blob/backend-failures/webapp/graphite/finders/utils.py#L71) and an example implementation of `fetch` in [RemoteFinder](https://github.com/DanCech/graphite-web/blob/backend-failures/webapp/graphite/finders/remote.py#L125) and [RemoteReader](https://github.com/DanCech/graphite-web/blob/backend-failures/webapp/graphite/readers/remote.py#L37) in my branch.

The implementation differs from graphite-api in that it allows the finder to totally skip the find cycle and instead just perform the fetch directly.  Note that `find_multi` is only used by `fetch` at present, the find HTTP API only supports specifying a single path so it only uses `find_nodes`.   Because of this `RemoteFinder` doesn't re-implement `find_multi` since its `fetch` implementation doesn't use it.
