### ISSUE TITLE
Graphite-web on ubuntu 16.04.3

### ISSUE THREAD

**Issue by R00T88** [graphite-project/graphite-web#2138]
Hello,
i install graphite on ubuntu 16.04.3 (apt-get install graphite-web) but the only version available on it is the 0.9.15.
Same happends for graphite-carbon.

Is it correct?

Regards

**Comment by deniszh** [comment]
Probably, yes - https://launchpad.net/ubuntu/+source/graphite-web
Unfortunately, we're not packing graphite into packages, distro owners doing that. Create deb or rpm for python package is easy, but many dependencies should be upgraded too, so, it's not that straightforward process, as expected. That's why 1.0.2 is presented only in upcoming (Bionic Beaver) ubuntu.
