### ISSUE TITLE
Upgrading graphite-web via pip caused pip to try and make a backup of /opt/graphite/storage to /tmp

### ISSUE THREAD

**Issue by wridgers** [graphite-project/graphite-web#2193]
Here is the command I used: `pip install --upgrade --install-option="--prefix=/opt/graphite" --install-option="--install-lib=/opt/graphite/webapp" graphite-web==1.1.1` (via ansible).

I noticed it was taking a long time and a colleague quickly ran a strace. We discovered that, as part of the uninstall step, pip was trying to copy `/opt/graphite/storage` to `/tmp/pip-somehash-uninstall`.

Am I doing something wrong here? It's pretty scary that pip would start doing things to my `.wsp` files when I try to upgrade a package.

**Comment by deniszh** [comment]
Yep, I remember similar report, but I was not able to reproduce that.
What's version of OS, python and pip?

**Comment by wridgers** [comment]
```
root@graphite2:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
root@graphite2:~# python --version
Python 2.7.12
root@graphite2:~# pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
root@graphite2:~# 
```

**Comment by deniszh** [comment]
That's funny. I was not able to reproduce on exact same config. Will try again.

**Comment by redbaron4** [comment]
So I ran into this problem again (with both carbon and graphite-web 1.1.2 using pip 9.0.1) and here is what I can summarize:

- pip install finds an existing older version (mostly 1.x) and uninstalls it.
- During uninstall it removes all the files that it remembers installing. (This list can be seen in `/opt/graphite/lib/carbon-1.1.1-py2.7.egg-info/installed-files.txt`).
- Unfortunately storage/ is in the file and hence is removed. Here is the trace when using debug option with pip

```
Installing collected packages: graphite-web
  Found existing installation: graphite-web 1.1.1
    Uninstalling graphite-web-1.1.1:
      Removing file or directory /opt/graphite/bin/build-index
      Removing file or directory /opt/graphite/bin/build-index.sh
      Removing file or directory /opt/graphite/bin/run-graphite-devel-server.py
      Removing file or directory /opt/graphite/conf/dashboard.conf.example
      Removing file or directory /opt/graphite/conf/graphTemplates.conf.example
      Removing file or directory /opt/graphite/conf/graphite.wsgi.example
      Removing file or directory /opt/graphite/examples/example-client.py
      Removing file or directory /opt/graphite/examples/example-graphite-vhost.conf
      Removing file or directory /opt/graphite/storage/ceres
      Removing file or directory /opt/graphite/storage/log
      Removing file or directory /opt/graphite/storage/rrd
      Removing file or directory /opt/graphite/storage/whisper
      Removing file or directory /opt/graphite/webapp/content/css/darkX.css
      Removing file or directory /opt/graphite/webapp/content/css/darkX/button-close-focused.png
      Removing file or directory /opt/graphite/webapp/content/css/darkX/button-maximize-focused.png
      Removing file or directory /opt/graphite/webapp/content/css/darkX/button-minimize-focused.png
```

- Next the install happens where these are recreated

```
copying webapp/content/js/ext/resources/images/default/shared/calendar.gif -> /opt/graphite/webapp/content/js/ext/resources/images/default/shared
    creating /opt/graphite/storage/whisper
    creating /opt/graphite/storage/ceres
    creating /opt/graphite/storage/rrd
    creating /opt/graphite/storage/log
    creating /opt/graphite/storage/log/webapp
    copying conf/dashboard.conf.example -> /opt/graphite/conf
    copying conf/graphite.wsgi.example -> /opt/graphite/conf
    copying conf/graphTemplates.conf.example -> /opt/graphite/conf
    copying examples/example-graphite-vhost.conf -> /opt/graphite/examples
    copying examples/example-client.py -> /opt/graphite/examples
```

I can understand the motivation of making all `storage/` paths as data files (so that users have minimal work to do). Unfortunately, pip protocol is somewhat different than what a more mature tools like RPM would provide and so it removes the directories even during an update. It may be possible to raise this issue with them but that will be long drawn process (if they do decide to fix it).
