### ISSUE TITLE
graphite-web and carbon, installed from 'pip' is broken if venv is used

### ISSUE THREAD

**Issue by Civil** [graphite-project/graphite-web#2205]
if you are installing in venv, you'll get following paths (relative to venv root):
```
./lib/python2.7/site-packages/opt/graphite/webapp
./lib/python2.7/site-packages/opt/graphite/lib/carbon/
./lib/python2.7/site-packages/opt/graphite/lib/twisted/
```

This is wrong and must be fixed.

**Comment by zasca** [comment]
This is due to changes in the pip versions.

Workarounds:
1. `pip install --no-binary=:all: <carbon/graphite-web>`
2. `pip install pip==6.1.1`
______

since [7.0.0](https://pip.pypa.io/en/stable/news/#id51) introduced: _build wheels prior to installing from sdist_
Affects to python package sources: `pip install <carbon/graphite-web>`

since [10.0.0b1](https://pip.pypa.io/en/stable/news/#b1-2018-03-31) introduced:
_packages which specify one or more build dependencies this way will be built into wheels_
Affects to VCS sources:
`pip install https://github.com/graphite-project/<carbon/graphite-web>/tarball/<tag/commit>`

**Comment by piotr1212** [comment]
I guess this should help too https://github.com/graphite-project/graphite-web/pull/2409
