### ISSUE TITLE
Bug: Metrics tree not loaded when CLUSTER_SERVERS member is unavailable - fixed just in 1.0

### ISSUE THREAD

**Issue by mcbsdEU** [graphite-project/graphite-web#2218]
Hi,

I refer to an issue #1791, this has been fixed in past, but seems just in 1.0.x.
1.1.x has different file structure and fix is not valid anymore.
In order to bypass the issue in very dirty way, I had to modify:
..graphite/finders/remote.py:
line 262: bypass Exception by inserting "return" right after:
```
        except BaseException as err:
            return
            self.fail()
            log.exception("RemoteFinder[%s] Error requesting %s: %s" % (self.host, url_full, err))
            raise Exception("Error requesting %s: %s" % (url_full, err))
```

line 116: same workaround as above:
```
                    result, buffer_size=settings.REMOTE_BUFFER_SIZE))
            except Exception as err:
                return
                self.fail()
                log.exception(
                    "RemoteFinder[%s] Error decoding find response from %s: %s" %
                    (self.host, result.url_full, err))
                raise Exception("Error decoding find response from %s: %s" % (result.url_full, err))
```

line 123: comment the  "finally" clause:
```
            #finally:
            #    result.release_conn()

            cache.set(cacheKey, results, settings.FIND_CACHE_DURATION)
```

It would be very very helpful to have this fixed in 1.1.x
It has huge importance for High Availability situations, when one node of cluster is down because with a current bug, whole solution is not available because of one non-functional node.

Thanks in advance!

FYI:
This is snippet of the error for future generations (affected node has no httpd running, otherwise it would shout out timeout error):
```
Exception: Error requesting http://a.b.c.d:80/metrics/find/?local=1&format=pickle&query=%2A: HTTPConnectionPool(hos
t='a.b.c.d', port=80): Max retries exceeded with url: /metrics/find/?local=1&format=pickle&query=%2A (Caused by New
ConnectionError('<urllib3.connection.HTTPConnection object at 0x56013b692490>: Failed to establish a new connection: [Errn
o 111] Connection refused',))
```

**Comment by deniszh** [comment]
@mcbsdEU : Thanks for reporting!
@DanCech @iksaif : It's about scenarion when one node of the cluster is down.
Previous fix of @iksaif is https://github.com/graphite-project/graphite-web/commit/c6cf8244862ec15bf25b4cb4b01a29e45f59e2eb
Do you  have an ideas how to fix that properly in current codebase?

**Comment by DanCech** [comment]
This is really a philosophical issue, should we return incomplete results or let the user know that it's not possible to compute a complete result?  There are a lot of scenarios where trying to continue even though a shard is unavailable will cause the results to be incorrect in ways that are non-obvious, a good example is when using `sumSeries` as the sum will just appear to be lower than normal.

My personal opinion is that in this case returning an error is the right thing to do.  If we want to enable this functionality it should be gated behind a configuration setting so the administrator of the system can acknowledge that they want the system to continue when a backend node is down and return most-likely-incorrect results.

The correct way to achieve high availability is to run backend shards as load-balanced pairs, so that the system can operate correctly when either one of each pair is unavailable.

**Comment by mcbsdEU** [comment]
@DanCech it is also valid point. Well it was already fixed once...
Maybe configuration parameter could be applied so setting that into "True" could continue with other node when previous one failed.
Also, it should log error in any case, the question is if it is reason to do exception and exit.

**Comment by deniszh** [comment]
>This is really a philosophical issue, should we return incomplete results or let the user know that it's not possible to compute a complete result?

Graphite is supporting replication, but it depends on metric name, so, real problem here is that we're do not know will result for specific query be complete or not if particular cluster node is down.
So, agreed with @DanCech here - this should be configurable option, but I can see valid usecases where we should return data even if one of the cluster node is down.

**Comment by mcbsdEU** [comment]
In our use-case, we are sending _same_ metrics in two parallel streams (into first node and into second node of cluster). So it behaves as active-active at the end.
When one node is down, etc. during maintenance, only second node receives metrics. When node which was down again is up and running and it receives query for metrics which for certain time came just into other node, it will "merge" results and provide complete response to requester.
I think the key point here is, that we send _same_ metrics to both.

**Comment by DanCech** [comment]
Yes, that would be a scenario where skipping a failed host would make sense.

**Comment by mcbsdEU** [comment]
So, will you include respective configuration option?

**Comment by mcbsdEU** [comment]
Hi,
is it still for discussion?
Thx

**Comment by DanCech** [comment]
If anyone wants to write a PR I'll be happy to review it.

**Comment by toerkl** [comment]
Hi. I would be happy to be able to set this parameter. I have an ELB with two graphite frontends that look into two backends with replicated data for high availability purposes. I would still want to return the result if one backend goes down. Or is there a better way to achieve high availability?

**Comment by clusterfudge** [comment]
@DanCech I've created #2303 in an attempt to address this issue (it works in my test cluster as expected). Care to take a look?

**Comment by deniszh** [comment]
Hmm... if I understand it correctly #2303 doing exact opposite thing and not really fixing this issue...

**Comment by mcbsdEU** [comment]
@clusterfudge Based on description @2303 I'd also say it seems to be opposite...
I'd like to write PR but I'm not really an expert in this...

**Comment by funtiik** [comment]
Hi guys,
Are there any plans/ideas on how to resolve this issue?
Thanks.

**Comment by clusterfudge** [comment]
So, there's a windy story here. 
1) In this original issue, mcbsdEU's complaint is that in 1.0.x, if any of CLUSTER_SERVERS is unavailable (or a request fails), all requests fail. 
2) mcbsdEU also brings to light that behavior is inconsistent between 1.0.x and 1.1.x, and the 1.1.x behavior is preferred.
3) In [Dan's comment](https://github.com/graphite-project/graphite-web/issues/2218#issuecomment-362283812), he states an opinion that mcbsdEU's complaint about 1.0.x is the correct behavior, and the behavior in 1.1.x is a regression.
4) In #2303 we opine that while the 1.1.x behavior may be a regression, it is now the expected behavior and a fix would have to preserve the existing behavior. As such, the fail-hard behavior is configurable and disabled by default.
5) #2303 is merged, and you can decide what is the appropriate behavior for you.

**Comment by mcbsdEU** [comment]
Hello @clusterfudge 
If it is true regarding #2303, then it seems all ok - it is configurable.
However, it is strange, we are using graphite-web-1.1.1-1.fc28.noarch on RHEL, and there is nothing like STORE_FAIL_ON_ERROR or REMOTE_STORE_HARD_FAILURES. Could you clarify this one?

Thanks

**Comment by clusterfudge** [comment]
#2303 hasn't made it into a release yet. @deniszh anything keeping it from getting into 1.1.4?

**Comment by mcbsdEU** [comment]
Ah I see....Ok, let's wait for @deniszh reply.

**Comment by deniszh** [comment]
Nothing, except careful backporting and preparing release notes. But not sure if I will make it soon, I was thinking about the end of August. Will try this weekend, but no promises.

**Comment by funtiik** [comment]
Hi @clusterfudge 
Regarding  #2303 I've tried setting the option STORE_FAIL_ON_ERROR = True and when one of the backend nodes is unavailable it still raises an exception and not returning the data.

**Comment by mcbsdEU** [comment]
@funtiik please check reply from @clusterfudge : "#2303 hasn't made it into a release yet."

**Comment by funtiik** [comment]
@mcbsdEU  #2303 is merged and I have used master branch.

**Comment by deniszh** [comment]
@funtiik: but that’s exactly what’s expected - it breaks on error, otherwise graphite will swallow unreachable backend error and produce wrong result.
Not really clear what you trying to achieve, could you please elaborate?

**Comment by mcbsdEU** [comment]
Hi,
after we did upgrade to latest Graphite, we could verify STORE_FAIL_ON_ERROR which is by default FALSE.
I can confirm that this configuration parameter addresses this issue, means it solves our problem and custom dirty patching is not needed any more.
Thank You
