### ISSUE TITLE
Graphs show no data for +6hours

### ISSUE THREAD

**Issue by lrhazi** [graphite-project/graphite-web#2253]
Hello,
What would cause graphite to show data for previous hour, 2,3,4,5 and 6 hours, but no data at all if I select any larger time span?

am using latest docker image graphiteapp/graphite-statsd

**Comment by deniszh** [comment]
Default storage schema is https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/conf/storage-schemas.conf
Default aggregation schema is https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/conf/storage-aggregation.conf
As you can see, default retention is `10s:6h,1m:6d,10m:1800d`, and default aggregation is `average` with `xFilesFactor = 0.3`.
That means that for every minute you need to send data at least 60 / 10 * 0.3 = 1.8 ~ 2 times, otherwise, Graphite will think that you have a gap in data, and it should not be propagated to next archive.
You can set `xFilesFactor = 0` in https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/conf/storage-aggregation.conf#L41 but then you need to delete and recreate your wsp files in `/opt/graphite/staorage/whisper` dir.

**Comment by lrhazi** [comment]
Thank you so much!

**Comment by Goldenflamer** [comment]
@deniszh How can I recreate the wsp files?

**Comment by deniszh** [comment]
@Goldenflamer 
if a file is absent it will be created by carbon automatically.

**Comment by Goldenflamer** [comment]
@deniszh Hmm, on my system they don't recreate...
I am using the official docker image with pretty much the default configuration:

First I initialised the container:
docker run -d\
 --name graphite\
 --restart=always\
 -p 80:80\
 -p 2003-2004:2003-2004\
 -p 2023-2024:2023-2024\
 -p 8125:8125/udp\
 -p 8126:8126\
 graphiteapp/graphite-statsd


Then after a few days I saw that there i no data after 6 hours so I went ahead and stopped the container with docker stop graphite and edited the storage conf at /opt/graphite/conf/storage-schemas.conf and deleted all the whisper files at /opt/graphite/storage/whisper.

Finally I started the docker image again with docker start graphite. Still even after days the whisper files are still missing and the configuration has not been applied properly, I don't see a change at all. What is my mistake?
