### ISSUE TITLE
applyByNode and time offset

### ISSUE THREAD

**Issue by index0h** [graphite-project/graphite-web#2316]
Graphite version: 1.1.3

Hi,
I have two types of metrics:

* prefix.service-{int: id}.income
* prefix.service-{int: id}.user

Their count not equal, and changes every day, for example:

* prefix.service-1.income
* prefix.service-2.income
* prefix.service-2.user

I need to calculate metric, which is sum of income by day divied by sum of user by day for every id.
I tried next query:

```
applyByNode(
    prefix.*.income,
    1,
    "divideSeries(
        summarize(%.income, '1day', 'sum', false),
        summarize(%.user, '1day', 'sum', false)
    )"
)
```

it works, but time of result near current UTC time, not 00:00:00. Also tried ugly hack by summarize result by day, it sets time to 00:00:00 but last day of period always 0.
If I calculate metrics for specific id, without applyByNode, it's ok.

Could you suggest some other way for my case? Thanks

**Comment by DanCech** [comment]
I'd recommend using [asPercent](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.asPercent) with the `nodes` parameter, and [smartSummarize](http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.smartSummarize) to get the right alignment (as it's timezone-aware), something like:

`aliasByNode(scale(asPercent(smartSummarize(prefix.*.user, '1day', 'sum', 'days'), smartSummarize(prefix.*.income, '1day', 'sum', 'days'),1), 0.01),1)`

The reason for using `asPercent` rather than `applyByNode` is that it doesn't have to re-evaluate the query like `applyByNode` does, so it should be a much faster.  The `scale(0.01)` is there because `asPercent` outputs the ratio as 0-100 rather than 0-1 so we multiply by 0.01 to get the result you're expecting.
