### ISSUE TITLE
diffSeries misbehaves when metrics contain missing data points

### ISSUE THREAD

**Issue by gksinghjsr** [graphite-project/graphite-web#2386]
DiffSeries behaves inconsistently when metrics contain null values, or are missing altogether.
Scenario 1. diffSeries(diff.test1,diff.test2)
If test1 and test2 contain some missing data points, the diffSeries result evaluates each timestamp independently. What this means is for the resulting diffSeries, each datapoint is calculated from a tuple where any null data points is ignored. At a given timestamp, if diff.test1 is null, the result would be the value at that timestamp for diff.test2, and vice-versa for the next timestamp. If diff.test1 is missing entirely, then the result is diff.test2.

Scenario 2. diffSeries(diff.test1, diff.test2 ... diff.testn)
In case of a series list of size n, what happens is an extension of the previous scenario.
If diff.test1 series is missing, the result would be diff.test2 subtracted by the sum of all the others.

In a generic scenario, for each diff series timestamp, the result is calculated by forming a tuple formed from the value at that timestamp for each series. From this, we remove all nulls (doesn't matter the position of the series). And from this shortened tuple, the result is obtained by subtracting sum of all others from the first value in the tuple. And since the nulls can vary across the different timestamps, in case of metrics with some nulls, we end up with a widely inconsistent result.

![diff_test1_test2](https://user-images.githubusercontent.com/858763/48851641-e01d3080-edab-11e8-8dc5-98cb8dad3b65.png)
![scenario1_diffseries](https://user-images.githubusercontent.com/858763/48851642-e0b5c700-edab-11e8-8efd-578d97b33a30.png)

**Comment by deniszh** [comment]
IMO 1) is logic behavior (we're doing that assumption, I mean, NULL=0 quite often in other functions too) but we can make it optional.
2) should be fixed, indeed.

**Comment by piotr1212** [comment]
Null != 0, doing it in other functions too does not make it correct. I'm definitely not suggesting to change the default but Null means that the value is unknown. 
Lets say the measurement dropped for whatever reason. For example, if you take the difference in temperature between Amsterdam and the Hague (in summer), if one measurement drops because of a network outage then it doesn't mean the difference is 25 degrees as we both know the weather is evenly bad in the whole country.

**Comment by dbartz** [comment]
Though the issue is quite old, someone who stumbles over this might find the following helpful:

For me, setting the XFilesFactor to a value above 0.5 solved this issue:
`diffSeries(#A, setXFilesFactor(#B, 0.6))`
https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.setXFilesFactor

Then, aggregation only happens if more than 50% of the data points are non-null.

In the above case, the diff results in null when one of the metrics is null - as the OP desired.

Example:
<img width="850" alt="xfilesfactor" src="https://user-images.githubusercontent.com/8957660/93621199-7f78d200-f9db-11ea-869d-631181823d83.png">

**Comment by deniszh** [comment]
@dbartz : cool trick, thanks for sharing!
