### ISSUE TITLE
have a basic docker image with just carbon and whisper (and for the other services)?

### ISSUE THREAD

**Issue by f1-outsourcing** [graphite-project/graphite-web#2444]
I want to move away from my influxdb. Currently I am using that with grafana.

I thought it would be easiest to adapt my collectd's to send data not to influx but to graphite(carbon/whisper), and change the dashboards in grafana to use the graphite data source.

So I really do not need (I think) anything other than carbon and whisper. And would like to use a docker image that has only these two services.
I think from a container deployment perspective, you even would like to have all these services separate, so you can scale them individually, not?

**Comment by deniszh** [comment]
Hi @f1-outsourcing ,

For using graphite you need all components installed, not only carbon. You can use official docker image https://github.com/graphite-project/docker-graphite-statsd for that, but I'm afraid scaling will be quite hard in this setup - you will need to run container with relay, multiple containers with carbon/graphite-web and multiple containers with clustering graphite-web. I would say, containerized setup is more for all in one and not for scaling.

**Comment by f1-outsourcing** [comment]
Hmmm, I don't even see statsd mentioned on the main website https://graphiteapp.org/. I really need also graphite-web when I am using grafana? Maybe would be nice to update the graphite website graphs with where statsd fits in.

**Comment by deniszh** [comment]
That’s because StatsD is not a part of Graphite and never was. It’s
separate product which producing Graphite compatible metrics. You can find
more info on StatsD website and wiki. Please also note that original StatsD
is probably outdated, there’re many compatible implementations exist.
You’ll definitely need graphite-web to work with Grafana. Carbon and
whisper only storing metrics, you need a component for retrieving them.
