### ISSUE TITLE
Result of function currentBelow not correct

### ISSUE THREAD

**Issue by ralphbr** [graphite-project/graphite-web#2448]
We are counting host up and down in two different graphs. The metrics contain 0 or 1 as values (icinga2 metadata).

Function 1 to count hosts in state up: 
countSeries(currentBelow(icinga2.*_mydomain_net.host.hostalive4.metadata.state, 1))

Function 2 to count host in state down:
fallbackSeries(countSeries(currentAbove(icinga2.*_mydomain_net.host.hostalive4.metadata.state, 0)),constantLine(0))

Function 1 is always counting all host, even the last state of a host is 1 = down, so its result is always the number of all hosts. 
 
We are using the actual graphite docker version.

**Comment by deniszh** [comment]
Hi @ralphbr ,

yes, in current implementation - https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L3039 - `currentBelow(x, n)` is just a syntactic sugar for `filterSeries(x, 'last', '<=', n)`.
If you need '<' instead of '<='- call [filterSeries](https://graphite.readthedocs.io/en/latest/functions.html?highlight=filterSeries#graphite.render.functions.filterSeries) directly:
`countSeries(filterSeries(icinga2.*_mydomain_net.host.hostalive4.metadata.state, 'last', '<', 1))`
