### ISSUE TITLE
functions like aggregate and groupByNodes docs and validation not in sync with allowed callbacks

### ISSUE THREAD

**Issue by Dieterbe** [graphite-project/graphite-web#2508]
some functions have a mismatch between aggregation callbacks that the code allows, what the docs say, and what validation checks for.

## example one. "aggregate".

`def aggregate` looks like so:
```
  # strip Series from func if func was passed like sumSeries
  rawFunc = func
  if func[-6:] == 'Series':
    func = func[:-6]

  consolidationFunc = getAggFunc(func, rawFunc)
...
Param('func', ParamTypes.aggFunc, required=True, options=aggFuncNames),
```

which refers to:
```
# Series Functions

aggFuncs = {
  'average': safeAvg,
  'avg_zero': safeAvgZero,
  'median': safeMedian,
  'sum': safeSum,
  'min': safeMin,
  'max': safeMax,
  'diff': safeDiff,
  'stddev': safeStdDev,
  'count': safeLen,
  'range': lambda row: safeSubtract(safeMax(row), safeMin(row)),
  'multiply': lambda row: safeMul(*row),
  'last': safeLast,
}

aggFuncAliases = {
  'rangeOf': aggFuncs['range'],
  'avg': aggFuncs['average'],
  'total': aggFuncs['sum'],
  'current': aggFuncs['last'],
}

aggFuncNames = sorted(aggFuncs.keys()) + sorted(aggFuncAliases.keys())

def getAggFunc(func, rawFunc=None):
  if func in aggFuncs:
    return aggFuncs[func]
  if func in aggFuncAliases:
    return aggFuncAliases[func]
  raise InputParameterError('Unsupported aggregation function: %s' % (rawFunc or func))
```
the docs say:
```
This function can be used with aggregation functions average (or avg), avg_zero, median, sum (or total), min, max, diff, stddev, count, range (or rangeOf) , multiply & last (or current).
```
-> while the validation (if enabled) disallows it, and the documentation doesn't mention it, aggregate accepts any aggregation function ending on "Series" which also exist as standalone processing functions (e.g. "maxSeries") or also ones that don't exist as standalone functions (e.g. "lastSeries")

## example two. groupByNode.

likewise, it declares its param like so:
```
  Param('callback', ParamTypes.aggFunc, required=True, options=aggFuncNames),
```

but the code does this:
```
    if callback in SeriesFunctions:
      metaSeries[key] = SeriesFunctions[callback](requestContext, metaSeries[key])[0]
    else:
      metaSeries[key] = aggregate(requestContext, metaSeries[key], callback)[0]
```

Docs:
```
This function can be used with all aggregation functions supported by aggregate: average, median, sum, min, max, diff, stddev, range & multiply.
```
-> as it calls `aggregate` it obviously suffers from the same discrepancy as aggregate explained above, but even more so `SeriesFunctions` is [a huge collection of functions](https://github.com/graphite-project/graphite-web/blob/021cfe62c836ec952e170e9cc7813efd34e02403/webapp/graphite/render/functions.py#L5786-L5951), while the validation doesn't allow anywhere near it, and the documentation doesn't mention them

**Comment by Dieterbe** [comment]
seems like the main 2 options are to relax the validation (especially if we've advertised previously that "fooSeries" are valid arguments), or removing the "strip Series from func if func was passed like sumSeries" clause otherwise.

thoughts @DanCech ?

**Comment by DanCech** [comment]
looks like the validation should be relaxed, I had forgotten about the old blahSeries support but we do want to maintain BC for that I think.  The simplest solution may be to just not restrict the options at the validation layer for these functions and allow `getAggFunc` to deal with throwing the error if a specified function isn't valid.

**Comment by replay** [comment]
I agree that the easiest fix to make it work would be to just not check that value in the validator.
But isn't the underlying issue actually that in the function definitions the given `options` define an incomplete set of valid values?
F.e. in the case of `groupByNodes` the valid options are defined to be `aggFuncNames`: https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L4996
which is not the complete set of valid options, because in reality the function can use all of `SeriesFunctions`: https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/render/functions.py#L5041
So i think the "proper" fix, even though it takes a bit longer, would be to update the definition of valid values

**Comment by DanCech** [comment]
To fix this properly we really need a way to communicate that various options are accepted but deprecated, the xSeries syntax for example shouldn't be used when writing queries, and there are a lot of series functions that won't actually work properly or don't make sense with groupByNode.

**Comment by replay** [comment]
If we already make this change, we might also want to add another option to the config to define whether the validation should accept deprecated options.

**Comment by replay** [comment]
With the recently merged PR https://github.com/graphite-project/graphite-web/pull/2513 the above examples should all work even with the input validation enabled, because all aggregator functions and their alias with the `+ 'Series'` suffix are accepted now. 

One thing which is still weird is the fact that in the code of the functions `groupByNode, groupByNodes, groupByTags` expects that the given aggregator function could also be any series processing function, like for example `groupByNodes(some.id.of.a.metric.*, "weightedAverage")`:
https://github.com/graphite-project/graphite-web/blob/52c0fd11a18de633e28e389d394ceba45a8e2831/webapp/graphite/render/functions.py#L4888
This is not documented, but the code appears to support that, even though in the case of most series processing functions it either doesn't work because the given arguments in the function call don't match what the series processing function expects, the return type of the series processing function doesn't match what the call site expects, or the result just makes no sense.
The specific example with `weightedAverage` doesn't work because the weighted average function call requires more arguments than only a list of series, resulting in a 5xx when it is used as an aggregator. On the other hand for example the series processing function `asPercent` works as an aggregator because it satisfies these 3 criteria:

1) First argument is a list of series
2) All other arguments are not required
3) Returns a list of series

So I'm worried some users might already be using series processing functions such as `asPercent` as aggregators, even though the support for this is not documented.
The problem for the input validation is that the criteria 1) and 2) can be detected by the input validation, but 3) cannot be detected because in Python there seems to be no practical way to obtain the return type from a defined function. As of the PR #2513 the input validation simply prohibits the use of any series processing functions as aggregators, including those few which might actually work and make sense like the example of `asPercent`.

I think if we want to also allow these series processing functions for which it makes sense as aggregators then we have 3 options:

1) Detect whether the expected list of arguments of each series processing function matches what the call site would pass it, and only allow those. This would remove most of the series processing functions from the list of allowed aggregators, meaning the input validation would be able to prevent a 5xx if a user tries to use them, but there are still going to be a few where the returned type doesn't match what the call site expects, resulting in a 5xx. This would mean that the input validation could not prevent all possible 5xx errors due to bad user input anymore, I have a PR where I tested that here: 
https://github.com/graphite-project/graphite-web/pull/2523
2) Go through the list of built-in series processing functions and manually pick the ones which can be used as an aggregator and mark them somehow, by setting some `.aggregator=True` property, that way the input validation could judge based on this property whether a series processing function may be used as aggregator. But this has the disadvantage that custom functions which have been created by users might not work as aggregators anymore, until they get updated to have that property.
3) The inverse of 2), which  would be to mark all those series processing functions which should not be used as aggregator functions with some property like `.aggregator=False`. That way the input validation could still detect whether the built-in series processing functions may be used as aggregators and then the default assumption would be that user defined custom functions may also be used as aggregators unless they're marked with that new property.

What do you think @DanCech

**Comment by replay** [comment]
This implements `2)` https://github.com/graphite-project/graphite-web/pull/2528

**Comment by replay** [comment]
Done, as https://github.com/graphite-project/graphite-web/pull/2528 is merged
