### ISSUE TITLE
[Q]Graphite tool not receiving all the the values and graph is missing

### ISSUE THREAD

**Issue by Rock-sa** [graphite-project/graphite-web#2599]
Hi
I am using module Net::Graphite. Sending value in hash, but graph is not plotting every minute. Our subroutine will be every miute from some external server.
$hash is {"1589458143":{"stat":1,"time_in_ms":"0.26"}}
$graphite_obj->send(
            data => $hash,
            path => $path,
);

**Comment by ploxiln** [comment]
If there are some data points, but also gaps, this can be due to the configured storage granularity, which is controlled by carbon-cache: https://github.com/graphite-project/carbon/blob/master/conf/storage-schemas.conf.example

(note that existing whisper storage files will not be changed automatically, you can either update them manually using whisper-resize, or you can delete the file and allow carbon-cache to re-create it with your new configuration)
