### ISSUE TITLE
Graphite 500 Internal server error and won't restart automatically when host reboots[Q]

### ISSUE THREAD

**Issue by cduncan224** [graphite-project/graphite-web#2623]
Every Saturday morning the host running graphite reboots however recently graphite fails to restart on its own as it used to and requires a manual restart from support. Logging through the logs there are three instances of the screen shotted error stating graphite has a 500 internal server error but I can not find the source of this error 

<img width="1421" alt="Screen Shot 2020-07-01 at 9 13 17 AM" src="https://user-images.githubusercontent.com/67697855/86254890-1ae86c80-bb7c-11ea-99b5-0f0982d71a10.png">

We are running Graphite web 0.9 on a CentOS 7 host. 
Any help with how to rectify this would be appreciative.

**Comment by ploxiln** [comment]
That's an old version of graphite-web which is no longer maintained. But maybe the issue is in configuration of the wsgi service or web-server or service manager or something else. But that screenshot is quite annoying to try to read, and the end is cut off. You should try to get a properly formatted backtrace, either from a browser loading that html that was logged, or from the wsgi service logs if it is separate from this.
