### ISSUE TITLE
[BUG] Issue in pulling metrics from more then 2 graphite node , Unable to fetch

### ISSUE THREAD

**Issue by AshishVerma7690** [graphite-project/graphite-web#2628]
I am running graphite cluster with three nodes ( working in docker environment)
below are my graphite local_setting 

for Node 1:
 
```
CLUSTER_SERVERS = ["172.16.2.47:8081", "172.16.0.41:8081"]
REMOTE_STORE_FETCH_TIMEOUT = 300   # Timeout to fetch series data
#REMOTE_STORE_FIND_TIMEOUT = 2.5  # Timeout for metric find requests
REMOTE_STORE_RETRY_DELAY = 60    # Time before retrying a failed remote webapp
#REMOTE_FIND_CACHE_DURATION = 300 # Time to cache remote metric find results
REMOTE_PREFETCH_DATA = True
CARBONLINK_HOSTS = ["127.0.0.1"]
CARBONLINK_TIMEOUT = 1.0
USE_WORKER_POOL = True
POOL_MAX_WORKERS = 10
```
For Node 2:
```
CLUSTER_SERVERS = ["172.16.5.36:8081", "172.16.0.41:8081"]
## Rest same as Node 1
```
For Node 3:
```
CLUSTER_SERVERS = ["172.16.2.47:8081", "172.16.5.36:8081"]
## Rest same as Node 1

```
I am using Grafana as fornt-End, When I use 2 Node only everything works fine but as soon as I switched to three node cluster I am starting facing issue while getting data. Below are the logs which i got 

```
020-07-30,10:38:42.816 :: Timed out after 300.000278s for fetch for ['*.collectd.memory']
2020-07-30,10:38:42.817 :: Timed out after 300.000224s for fetch for ['*.statsd.memory']
```

**Environment (please complete the following information):**
 - OS flavor: Ubuntu
 - Graphite-web version - 1.1.5
 - Django/Python version - 2.0.13/Python3.6

**Comment by deniszh** [comment]
@AshishVerma7690 : yes, that setup is possible and should work - graphite-web emits '?local=1' parameter when calling CLUSTER_SERVERS and they should lookup only local files and not create any loops.
But I personally always prefer 2 tier setup - why not setup Node1 as requestor for other 3 nodes, e.g.

`CLUSTER_SERVERS = ["172.16.5.36:8081","172.16.0.41:8081","172.16.2.47:8081", ]`

and use Node2, Node3 only for reading local files and serve them to Node1 requests', i.e.

`CLUSTER_SERVERS = []`

**Comment by deniszh** [comment]
Will try to reproduce 3 node setup with cross requests, when I'll have time later, though, as I said it should work.

**Comment by AshishVerma7690** [comment]
@deniszh  In my scenario, I am not certain how many graphite node will be there, it will be a run time value. User can scale up nodes and also scales down. Also my data is distributed through multiple graphite node. 
As of now I am fetching data using grafana-ui (running in same docker with graphite - Node 0)  which fetch from cluster nodes.

**Comment by deniszh** [comment]
In my scenario you're on same scalability as in your setup, it's just less complex, hence less error prone to complex bugs, similar to this one.

**Comment by AshishVerma7690** [comment]
> In my scenario you're on same scalability as in your setup, it's just less complex, hence less error prone to complex bugs, similar to this one.

In your scenario, you are using Node1 for read purpose, but what happen if the node1 itself goes down?

**Comment by deniszh** [comment]
> In your scenario, you are using Node1 for read purpose, but what happen if the node1 itself goes down?

If you want to protect from this scenario you need to set another node with absolutely same setup as node0 and put read requests there, using load balancer or DNS. In your setup you need to do similar thing anyway.
As I said, it's 2-tier system - first tier of N nodes are contains no data, they're just getting requests from 2nd tier and render them to users. And 2nd tier of M nodes only serving data from WSP files (but not spending resources for render data):

NodeT1-1:
`CLUSTER_SERVERS = ["NodeT2-1", "NodeT2-2", "NodeT2-3"..."NodeT2-M"]`
NodeT1-2:
`CLUSTER_SERVERS =  ["NodeT2-1", "NodeT2-2", "NodeT2-3"..."NodeT2-M"]`
...
NodeT1-N:
`CLUSTER_SERVERS =  ["NodeT2-1", "NodeT2-2", "NodeT2-3"..."NodeT2-M"]`

NodeT2-1:
`CLUSTER_SERVERS = []`
NodeT2-2:
`CLUSTER_SERVERS = []`
NodeT2-3:
`CLUSTER_SERVERS = []`
...
NodeT2-M:
`CLUSTER_SERVERS = []`

In your setup this 2 roles are mixed, which is not bad per se - but just can add complexity to setup. 
Also, in 2 tier setup you can replace 2nd tier nodes e.g. with `go-carbon` with carbonserver enabled - and system will still be working.
Your setup also should work, I'm just want to let you know that you can try different setup, which will decrease complexity and improve your results. It's not better or worse  - it's just another way which you can try.
But you're right - in general case two tier setup can require more nodes - 5 instead of 3 in your case. And in your setup you can use same nodes - in case of 2 tier setup they probably should differ.

**Comment by AshishVerma7690** [comment]
I can not use 2 Tier setup( 1 for reading & 1 for writing ) as  the graphite nodes are selected on run time using HAProxy. So I don;t know which is going to be my read node.

**Comment by deniszh** [comment]
Hi @AshishVerma7690 ,

sorry, I can't reproduce problem with latest Graphite.
I created simple 3 node cluster with similar configuration - relay, consistant hashing with RF=2 and every node reads data from other 2 nodes - https://github.com/graphite-project/graphite-test-docker/blob/master/cluster/docker-compose.yml

For me this setup works fine. I run `haggar` for some time (it's Graphite load generator) and then count metric on every node with 
`http://localhost:81/render/?format=json&target=countSeries(haggar.agent.0.metrics.*)&from=-1min` 
`http://localhost:82/render/?format=json&target=countSeries(haggar.agent.0.metrics.*)&from=-1min` 
`http://localhost:83/render/?format=json&target=countSeries(haggar.agent.0.metrics.*)&from=-1min` 

It gives me proper result - monotonically increase number.

**Comment by DanCech** [comment]
You can also set `REMOTE_EXCLUDE_LOCAL = True` in your `local_settings.py` and use the same `CLUSTER_SERVERS` on all hosts.  Graphite will automatically detect which of the IPs is local and only send the remote render requests to the other 2.

**Comment by AshishVerma7690** [comment]
> Hi @AshishVerma7690 ,
> 
> sorry, I can't reproduce problem with latest Graphite.
> I created simple 3 node cluster with similar configuration - relay, consistant hashing with RF=2 and every node reads data from other 2 nodes - https://github.com/graphite-project/graphite-test-docker/blob/master/cluster/docker-compose.yml
> 
> For me this setup works fine. I run `haggar` for some time (it's Graphite load generator) and then count metric on every node with
> `http://localhost:81/render/?format=json&target=countSeries(haggar.agent.0.metrics.*)&from=-1min`
> `http://localhost:82/render/?format=json&target=countSeries(haggar.agent.0.metrics.*)&from=-1min`
> `http://localhost:83/render/?format=json&target=countSeries(haggar.agent.0.metrics.*)&from=-1min`
> 
> It gives me proper result - monotonically increase number.

Ok I am able to get the desired result , but a new problem arrives now. I am now working with 6 node cluster and a lot of metrics .everything works fine if we collect data of last 15 min but as soon as I go for last 7 days data It hung up( It takes too much of time). 
Can we do anything to reduce this time period?

**Comment by AshishVerma7690** [comment]
working fine using cluster server
