### ISSUE TITLE
[Q] summarize() function explanation

### ISSUE THREAD

**Issue by VtG242** [graphite-project/graphite-web#2629]
When a summarize() function with 1day interval and sum aggregation function is used like in example below:
`summarize(some.metric, '1d', 'sum')`
so everything is OK if data range interval is set up to 30 days but for a longer intervals an Y axis values are changed in strange way.

See attached pictures for better imagination:
[30 days](https://www.dropbox.com/s/5l2evhyx5aeldgo/30_days.png?dl=0)
[31 days](https://www.dropbox.com/s/wjqvc4u4o9p2ncb/31_days.png?dl=0)

Is this  expected behaviour?

**Comment by ploxiln** [comment]
This is most likely related to your carbon [storage-schemas.conf](https://github.com/graphite-project/carbon/blob/master/conf/storage-schemas.conf.example) and [storage-aggregation.conf](https://github.com/graphite-project/carbon/blob/master/conf/storage-aggregation.conf.example) - your `storage-schemas.conf` tells carbon to keep a higher resolution for just 30 days, and a lower resolution for a longer period, and your `storage-aggregation.conf` tells carbon to average values when copying from the higher-resolution to lower-resolution series. Then, when you tell `graphite-web` to go back further than 30 days, it skips the higher resolution series completely, and only uses the lower-resolution series (because it wants to use a single resolution variant to cover the entire period).

If you configure your `storage-aggregation.conf` to aggregate to the lower resolution using "sum" for this series, that should  fix this problem. (These settings automatically apply only when the whisper storage file is initially created for a series, so you'll have to manually apply the change to the whisper file using the whisper utilities, or blow away the data and allow it to be re-created).

**Comment by VtG242** [comment]
Thank you for explanation. I will check the configuration files.
