### ISSUE TITLE
enhancement : stagger dashboard graphs

### ISSUE THREAD

**Issue by salerth** [graphite-project/graphite-web#28]
Using saved dashboards with multiple graphs (e.g. 9 default sized graphs (3x3)) can be very slow to load and refresh as all 9 graph requests hit apache at once.  

Would be good to be able to stagger the requests on first load, but more importantly on refresh/scheduled refresh.

**Comment by obfuscurity** [comment]
Given that nobody has stepped up to tackle this request in the 4 years since its submission, and the ubiquity of Grafana as the dashboard of choice, I think it's unlikely that we'll find spare cycles to hack on this. I'm going to close this for now but I'm happy to assist anyone that wishes to take a stab at this request.
