### ISSUE TITLE
keepLastValue does not look beyond given interval - annoying feature or a bug?

### ISSUE THREAD

**Issue by plebedev** [graphite-project/graphite-web#451]
Suppose you have two series:
A
timestamp  value
1                 500
2                  None
3                 1000
4                 1500

B
timestamp  value
1                 500
2                 1500
3                 2000
4                 2500

When you do sumSeries(keepLastValue(A.count),keepLastValue(B.count)) from ts 1, you get nice result:
1                 1000
2                 2000
3                 3000
4                 4000

However, if you do the same from ts 2 you will get this:
2                 1500
3                 3000
4                 4000

So, there will be a big jump from 2 to 3. 
This happens because keepLastValue uses only the data that corresponds to a given time frame (which is understandable) but it is really annoying and makes graphs not usable at all. 

Would it be possible to look back beyond the given 'from' timestamp to actually keep last value?

Attached are two screenshots that show the issue. It is the same data collected for past 1 hour and past 3 hours. 1 hour graph jumps from 0 to 30K because of this issue, while 3 hours graph is nice and smooth. 

![screen shot 2013-10-03 at 11 01 41 am](https://f.cloud.github.com/assets/5315507/1262271/ce119f6a-2c3c-11e3-9c95-f9d8bd04c246.png)
![screen shot 2013-10-03 at 11 02 06 am](https://f.cloud.github.com/assets/5315507/1262273/d39a1098-2c3c-11e3-8457-f3a17390f527.png)

Thanks,
Peter.

**Comment by deepakkamesh** [comment]
+1 this would be a good feature.

**Comment by DanCech** [comment]
In order to implement this, `keepLastValue` would need to be updated to check whether the first value of each series was `None` and if so get the previous `limit` values (would need to decide on a sensible maximum when `limit = INF`) to try and find the previous non-`None` value to start from, much like `movingWindow` does to bootstrap the aggregation.  We wouldn't want to do it unless the first value is `None`, because making the additional sub-request to get those earlier values requires another query to the data store.
